### ISSUE TITLE
[BUG]:  Building an application for ios Simulator fails.

### ISSUE THREAD

**Issue by smocken78** [gunschu/jitsi_meet#309]
**jitsi_meet plugin version**
jitsi_meet: 4.0.0

**Describe the bug**
Building an application for ios Simulator fails.

**Flutter doctor -v**
[✓] Flutter (Channel stable, 2.5.0, on macOS 11.5.2 20G95 darwin-x64, locale
    de-DE)
    • Flutter version 2.5.0 at /opt/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 4cc385b4b8 (vor 4 Tagen), 2021-09-07 23:01:49 -0700
    • Engine revision f0826da7ef
    • Dart version 2.14.0

[!] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/smocken/Library/Android/sdk
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for
      more details.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 12.5.1, Build version 12E507
    • CocoaPods version 1.11.0

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.0)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin version 49.0.2
    • Dart plugin version 193.7547
    • Java version OpenJDK Runtime Environment (build
      1.8.0_242-release-1644-b3-6222593)

[✓] VS Code (version 1.60.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

**Error Logs**
    objective-c com.apple.compilers.llvm.clang.1_0.compiler
    /opt/flutter/.pub-cache/hosted/pub.dartlang.org/jitsi_meet-4.0.0/ios/Classes/JitsiViewController.swift:8:41: error:
    cannot find type 'PiPViewCoordinator' in scope
        fileprivate var pipViewCoordinator: PiPViewCoordinator?
                                            ^~~~~~~~~~~~~~~~~~
    /opt/flutter/.pub-cache/hosted/pub.dartlang.org/jitsi_meet-4.0.0/ios/Classes/JitsiViewController.swift:87:30: error:
    cannot find 'PiPViewCoordinator' in scope
            pipViewCoordinator = PiPViewCoordinator(withView: jitsiMeetView)
                                 ^~~~~~~~~~~~~~~~~~
    /opt/flutter/.pub-cache/hosted/pub.dartlang.org/jitsi_meet-4.0.0/ios/Classes/JitsiViewController.swift:102:30: error:
    'nil' requires a contextual type
            pipViewCoordinator = nil
                                 ^
    /opt/flutter/.pub-cache/hosted/pub.dartlang.org/jitsi_meet-4.0.0/ios/Classes/JitsiViewController.swift:8:41: error:
    cannot find type 'PiPViewCoordinator' in scope
        fileprivate var pipViewCoordinator: PiPViewCoordinator?
                                            ^~~~~~~~~~~~~~~~~~
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code

**Comment by buzzwin** [comment]
Please try to delete podfile.lock . Run a pod repo update and then run the project again

**Comment by smocken78** [comment]
Thank you for your answer, but i am still getting the same error.

**Comment by smocken78** [comment]
I managed to get it running again with the following steps: 

flutter clean
pod repo update
cd ios
rm -rf Podfile.lock Pods/
cd ..
rm -rf pubspec.lock .packages .flutter-plungins
flutter pub pub cache repair
flutter packages get
cd ios
pod install

and finally starting the app from xcode

**Comment by rwbr** [comment]
I have the same problem. It appears after the upgrade of Flutter from 2.2.3 to 2.5.0. When I run the project from inside Xcode all just works. But I get the same error when trying to run the project from the terminal. Nothing of the hints given above helped.

**Comment by rwbr** [comment]
I can confirm that this problem has something to do with the Flutter upgrade. After a downgrade from Flutter 2.5.0 down to 2.2.3 again running the app in the simulator from the terminal with `flutter run` works fine.

**Comment by smocken78** [comment]
Yes, i just recognized that when i run the project from terminal it still fails.
But i am not sure if i should reopen the issue.

**Comment by rwbr** [comment]
I think, you should reopen it. It's not solved yet. Building with Xcode only is not an option in my case. My setup is different. I wish, this issue could become solved completely.

**Comment by smocken78** [comment]
Reopened as the problem is still present when building from command line

**Comment by rwbr** [comment]
It*s strange, but I can't reproduce this bug anymore. I upgraded Flutter to version 2.5.1 and Xcode to 13.0 in the meantime. Maybe we can close this one, if somebody can confirm this.

```
❯ flutter doctor -v                                                                                          [22:38:29]
[✓] Flutter (Channel stable, 2.5.1, on macOS 11.6 20G165 darwin-x64, locale de-DE)
    • Flutter version 2.5.1 at /Users/ralfweinbrecher/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision ffb2ecea52 (11 days ago), 2021-09-17 15:26:33 -0400
    • Engine revision b3af521a05
    • Dart version 2.14.2

[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.2)
    • Android SDK at /Users/ralfweinbrecher/Library/Android/sdk/
    • Platform android-30, build-tools 29.0.2
    • ANDROID_HOME = /Users/ralfweinbrecher/Library/Android/sdk/
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Xcode 13.0, Build version 13A233
    • CocoaPods version 1.10.1

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.60.2)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.26.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 11.6 20G165 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 93.0.4577.82
```

**Comment by rwbr** [comment]
Even the example doesn't compile for the iOS Simulator. 

What is different, when running the project from Xcode? Why dow it work then?

**Comment by rwbr** [comment]
And what difference does to Flutter version make? 
>= 2.5.0 *fails*
<2.5.0 *works*
Does the iOS SDK gets build differently depending on the Flutter version?

**Comment by smocken78** [comment]
I guess it is some kind of Classpath/Path problem, as when you build from xcode your working directory differs,

**Comment by truly6ve** [comment]
Hi,

I have the same issue and have tried the above instruction but didn't work for me. Using the latest Flutter version, i.e. 2.5.2.

**Comment by mojtabaghiasi** [comment]
same issue

**Comment by VietThang-Antoree** [comment]
same issue

**Comment by VietThang-Antoree** [comment]
it worked after I switched to beta channel, the version is 2.8.0-3.1.pre

**Comment by truly6ve** [comment]
Hi,

Finally, I got the solution to this issue. I edited the podfile with the following line: 

config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"

=======AS SHOWN IN THE EXAMPLE========
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
    end
  end
end

=======================================

Then:

1-> Open your project in Xcode 12 (or higher) and click on the targets
2-> Navigate to Build Settings of your project.
3-> Add Any iOS Simulator SDK with value arm64 inside Excluded Architectures.

then run "pod install" inside the ios folder and run build iOS app from xCode and it'll solve the issue.

Below is the link for full instructions which I follow...

https://milanpanchal24.medium.com/xcode-12-building-for-ios-simulator-but-linking-in-object-file-built-for-ios-file-for-8c0cc28ec832

You can use all other general commands like cleaning the flutter, repairing the packages etc. Let me know if you need any help.

I AM USING M1 WITH MACOS MONTEREY, VERSION 12.0.1 AND XCODE VERSION Version 13.1 (13A1030d).

**Comment by saibotma** [comment]
Works again with Flutter 2.8

**Comment by lubritto** [comment]
> Works again with Flutter 2.8

Still getting this issue!

Flutter (Channel stable, 2.8.1, on macOS 12.0.1 21A559 darwin-arm, locale
    en)

**Comment by rogeriomq** [comment]
Some problem, my environment:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.10.0, on macOS 12.2 21D49 darwin-x64, locale en-BR)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.1)
[✓] VS Code (version 1.64.0)
[✓] Connected device (2 available)
[✓] HTTP Host Availability


```
flutter run 
Launching lib/main.dart on iPhone 13 mini in debug mode...
Running Xcode build...                                                  
Xcode build done.                                            4.2s
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    Writing result bundle at path:
        /var/folders/1v/w8k82_2d5yb9vbxgvpq5nsn00000gn/T/flutter_tools.gZQGpl/flutter_ios_build_temp_dirS0vFRM/temporary_xcresult_bundle

    Command CompileSwiftSources failed with a nonzero exit code
    /Users/destroyer/flutter/.pub-cache/hosted/pub.dartlang.org/jitsi_meet-4.0.0/ios/Classes/JitsiViewController.swift:8:41: error:
    cannot find type 'PiPViewCoordinator' in scope
        fileprivate var pipViewCoordinator: PiPViewCoordinator?
                                            ^~~~~~~~~~~~~~~~~~
    /Users/destroyer/flutter/.pub-cache/hosted/pub.dartlang.org/jitsi_meet-4.0.0/ios/Classes/JitsiViewController.swift:87:30: error:
    cannot find 'PiPViewCoordinator' in scope
            pipViewCoordinator = PiPViewCoordinator(withView: jitsiMeetView)
                                 ^~~~~~~~~~~~~~~~~~
    /Users/destroyer/flutter/.pub-cache/hosted/pub.dartlang.org/jitsi_meet-4.0.0/ios/Classes/JitsiViewController.swift:102:30: error:
    'nil' requires a contextual type
            pipViewCoordinator = nil
                                 ^
    /Users/destroyer/flutter/.pub-cache/hosted/pub.dartlang.org/jitsi_meet-4.0.0/ios/Classes/JitsiViewController.swift:8:41: error:
    cannot find type 'PiPViewCoordinator' in scope
        fileprivate var pipViewCoordinator: PiPViewCoordinator?
                                            ^~~~~~~~~~~~~~~~~~
    note: Using new build system
    note: Planning
    note: Build preparation complete
    note: Building targets in dependency order

    Result bundle written to path:
        /var/folders/1v/w8k82_2d5yb9vbxgvpq5nsn00000gn/T/flutter_tools.gZQGpl/flutter_ios_build_temp_dirS0vFRM/temporary_xcresult_bundle


Uncategorized (Xcode): Command CompileSwiftSources failed with a nonzero exit code


Swift Compiler Error (Xcode): Cannot find type 'PiPViewCoordinator' in scope
/Users/destroyer/flutter/.pub-cache/hosted/pub.dartlang.org/jitsi_meet-4.0.0/ios/Classes/JitsiViewController.swift:7:40


Swift Compiler Error (Xcode): Cannot find 'PiPViewCoordinator' in scope
/Users/destroyer/flutter/.pub-cache/hosted/pub.dartlang.org/jitsi_meet-4.0.0/ios/Classes/JitsiViewController.swift:86:29


Swift Compiler Error (Xcode): 'nil' requires a contextual type
/Users/destroyer/flutter/.pub-cache/hosted/pub.dartlang.org/jitsi_meet-4.0.0/ios/Classes/JitsiViewController.swift:101:29


Could not build the application for the simulator.
Error launching application on iPhone 13 mini.
```

**Comment by ltoenjes** [comment]
Still happening on v 2.10.1

**Comment by sefrima** [comment]
I'm still getting this issue on flutter v2.10.4, Dart v2.16.2

**Comment by jesusdourado** [comment]
I'm also getting this issue on flutter v 2.10.4 Dart v2.16.2

**Comment by jesusdourado** [comment]
> I managed to get it running again with the following steps:
> 
> flutter clean pod repo update cd ios rm -rf Podfile.lock Pods/ cd .. rm -rf pubspec.lock .packages .flutter-plungins flutter pub pub cache repair flutter packages get cd ios pod install
> 
> and finally starting the app from xcode

this solution worked for me
